apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: ipapko test2
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          sleep 2m
          echo "hello world"
