apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow 3
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world workflow 3"
on:
  push:
    branches:
      - main+
  workflow_dispatch:
