apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      env1:
        type: string
jobs:
  build:
    environment: ${{ inputs.env1 }}
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        name: Say hello
        shell: sh
        run: |
          sleep 60s
          echo "hello world wf1 main"
